import os

DEBUG = False
SERVER_ENV = os.getenv('PYTHON_ENV', 'production')
SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False
JSONIFY_PRETTYPRINT_REGULAR = False
